services:
  postgres:
    image: postgres:16-alpine
    container_name: where-db
    environment:
      POSTGRES_DB: where
      POSTGRES_USER: where
      POSTGRES_PASSWORD: where123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata:
