databases:
  - name: geo-doido-db
    plan: free
    region: oregon
    postgresMajorVersion: 16

services:
  - type: web
    name: geo-doido
    runtime: node
    repo: https://github.com/DevPublishComunicacao/geo-doido
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: FRONTEND_URL
        value: https://geo-doido.onrender.com
      - key: SESSION_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: geo-doido-db
          property: connectionString
      - key: DB_HOST
        fromDatabase:
          name: geo-doido-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: geo-doido-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: geo-doido-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: geo-doido-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: geo-doido-db
          property: password
